import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { writeFileSync, readFileSync } from 'node:fs';
import { performance } from 'node:perf_hooks';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PATHWAYS_BASE || 'http://127.0.0.1:4321';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const results = [];
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.on('pageerror', e => errors.push(e.message));
const check = (condition, label) => { assert(condition, label); results.push(label); };
const selected = () => page.locator('[data-course-detail]:visible').getAttribute('data-course-detail');
const node = code => page.locator(`.path-node[data-course="${code}"]`);
const selectCourse = code => node(code).dispatchEvent('click');
const ready = () => page.waitForSelector('[data-course-paths][data-ready="true"]');
const reset = async () => { await page.goto(`${base}/latex/pathways/`); await ready(); };
try {
  await page.goto(`${base}/latex/pathways/`); await ready();
  check(await page.locator('[data-zoom-value]').textContent() === '50%', 'Desktop opens in the complete 50% overview');
  check(await page.getByText('课程范围与关系依据').count() === 0, 'Removed scope-and-sources disclosure is absent');
  check(await page.locator('.path-node').count() === 24, '24 rendered graph nodes');
  check(await page.locator('.path-row-nav, .path-track__label, .path-index').count() === 0, 'No visible category navigation, row labels or duplicate course table');
  const cross = await page.evaluate(() => {
    const nodes = [...document.querySelectorAll('.path-node')].map(n => ({ id: n.dataset.course, x: parseFloat(n.style.left), y: parseFloat(n.style.top) }));
    const hits = [];
    for (const path of document.querySelectorAll('[data-edge-from]')) {
      for (let i = 0; i < path.getTotalLength(); i += 3) {
        const p = path.getPointAtLength(i);
        const node = nodes.find(n => p.x > n.x + 1 && p.x < n.x + 171 && p.y > n.y + 1 && p.y < n.y + 69);
        if (node) { hits.push(`${path.dataset.edgeFrom}->${path.dataset.edgeTo}:${node.id}`); break; }
      }
    }
    return hits;
  });
  check(cross.length === 0, `Edges avoid all course boxes (${cross.join(',')})`);
  const data = JSON.parse(readFileSync(new URL('../../src/data/course-paths.json', import.meta.url)));
  for (const course of data.courses) {
    await selectCourse(course.code);
    check(await selected() === course.code, `Select ${course.code}`);
    const expected = data.edges.filter(e => e.to === course.code && e.kind === 'hard').length;
    check(await page.locator(`[data-course-detail="${course.code}"] [data-detail-group="hard"] li`).count() === expected, `${course.code} hard foundations correct`);
    check(await page.locator(`[data-course-detail="${course.code}"] [data-detail-group="soft"] li`).count() === data.edges.filter(e => e.to === course.code && e.kind === 'soft').length, `${course.code} soft foundations correct`);
    check(await page.locator(`[data-course-detail="${course.code}"] [data-detail-group="next"] li`).count() === data.edges.filter(e => e.from === course.code).length, `${course.code} downstream courses correct`);
  }
  await selectCourse('QM'); await selectCourse('QM');
  check(await selected() === 'QM', 'Repeated selection is stable');
  await page.locator('[data-relation="soft"]').click();
  await page.locator('[data-path-focus]').click();
  check(await page.locator('.path-node:visible').count() < 24, 'Focus reduces graph to direct relationships');
  check(await node('FA').isVisible(), 'Soft foundation visible in focused graph');
  await page.locator('[data-relation="hard"]').click();
  check(!await node('FA').isVisible(), 'Hard mode removes soft-only course from focused graph');
  await page.reload(); await ready();
  check(await selected() === 'QM' && await page.locator('[data-path-focus]').getAttribute('aria-pressed') === 'true', 'Refresh restores selected course, filters and focus');
  await reset();
  check(await page.locator('.path-node:visible').count() === 24, 'Reset restores complete map');
  check(await page.locator('[data-relation][aria-pressed="true"]').count() === 1, 'Exactly one relation mode is selected');
  await page.locator('[data-relation="soft"]').click();
  check(await page.locator('[data-edge-kind="hard"]').evaluateAll(paths => paths.every(p => getComputedStyle(p).opacity === '0')), 'Soft mode hides every hard edge');
  await page.locator('[data-relation="all"]').click();
  check(await page.locator('[data-edge-kind]').evaluateAll(paths => paths.every(p => getComputedStyle(p).opacity !== '0')), 'All mode shows both edge types');
  await page.locator('[data-relation="all"]').click();
  check(await page.locator('[data-relation][aria-pressed="true"]').count() === 1, 'Clicking selected relation mode cannot clear it');
  await reset();
  await selectCourse('QM'); await selectCourse('GR'); await page.goBack();
  check(await selected() === 'QM', 'Back restores prior course');
  await page.goForward(); check(await selected() === 'GR', 'Forward restores next course');
  await reset();
  await page.locator('[data-path-search]').fill('Quantum');
  check(await page.locator('.path-node:not(.is-muted)').count() === 2, 'English search highlights QM and QFT');
  await page.locator('[data-path-search]').fill('不存在的课程');
  check((await page.locator('[data-path-status]').textContent()).includes('找到 0 门课程'), 'Search reports an empty result');
  await reset();
  check(await page.locator('[data-zoom-value]').textContent() === '50%', 'Reset opens in the complete 50% overview');
  await page.locator('[data-zoom="in"]').click();
  await page.waitForTimeout(30);
  const initialZoom = await page.locator('[data-zoom-value]').textContent();
  check(initialZoom === '60%', 'Plus increases zoom by exactly 10%');
  check(Math.abs(await page.locator('[data-path-viewport]').evaluate(e => Number(e.dataset.zoom) * 100) - 60) < .001, 'Zoom display matches actual scale');
  await page.locator('[data-zoom="out"]').click();
  await page.waitForTimeout(30);
  check(await page.locator('[data-zoom-value]').textContent() === '50%', 'Minus decreases zoom by exactly 10%');
  await page.locator('[data-zoom="in"]').click();
  await page.waitForTimeout(30);
  while (!await page.locator('[data-zoom="in"]').isDisabled()) { await page.locator('[data-zoom="in"]').click(); await page.waitForTimeout(30); }
  check(await page.locator('[data-zoom-value]').textContent() === '240%', 'Zoom has upper bound');
  while (!await page.locator('[data-zoom="out"]').isDisabled()) { await page.locator('[data-zoom="out"]').click(); await page.waitForTimeout(30); }
  check(await page.locator('[data-zoom-value]').textContent() === '20%', 'Zoom has integer-ten lower bound');
  await page.locator('[data-path-viewport]').hover(); await page.mouse.wheel(0, 120); await page.waitForTimeout(30);
  check(await page.locator('[data-zoom-value]').textContent() === '20%', 'Lower bound remains stable');
  await page.locator('[data-zoom="read"]').click(); await page.waitForTimeout(30);
  await page.locator('[data-zoom="in"]').click(); await page.waitForTimeout(30);
  await page.locator('[data-path-viewport]').scrollIntoViewIfNeeded();
  const box = await page.locator('[data-path-viewport]').boundingBox();
  await page.mouse.move(box.x + box.width - 35, box.y + 25); await page.mouse.down();
  await page.mouse.move(box.x + 35, box.y + 25, { steps: 6 }); await page.mouse.up();
  check(await page.locator('[data-path-viewport]').evaluate(e => Number(e.dataset.panX)) < 0, 'Mouse drag pans the enlarged map');
  await page.locator('[data-zoom="fit"]').click();
  await page.waitForTimeout(30);
  check(await page.locator('[data-zoom-value]').textContent() === '50%', 'Fit returns to the complete 50% overview');
  await page.locator('[data-zoom="read"]').click();
  await page.waitForTimeout(30);
  check(await page.locator('[data-zoom-value]').textContent() === '100%', '100% button restores exact scale');
  await reset();
  await page.locator('.path-node[data-course="LA"]').focus(); await page.keyboard.press('Enter');
  check(await selected() === 'LA', 'Keyboard selects a course');
  await page.keyboard.press('Escape');
  check(await page.locator('[data-path-welcome]').isVisible(), 'Escape clears selection');
  const started = performance.now();
  for (let i=0; i<50; i++) await selectCourse(i%2 ? 'QM' : 'GR');
  check(await selected() === 'QM', '50 rapid selections leave consistent state');
  results.push(`50 selections: ${Math.round(performance.now()-started)} ms including automation`);
  await reset();
  for (const [width,height] of [[320,800],[360,800],[768,1024],[1024,768],[1440,900],[2560,1440],[3840,2160],[844,390]]) {
    await page.setViewportSize({ width,height }); await page.waitForTimeout(150);
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${width}x${height}: no horizontal page overflow`);
    check(await page.locator('.path-node').count() === 24, `${width}x${height}: all courses available`);
    await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo({top:0,behavior:'instant'}); });
    await page.screenshot({ path: new URL(`./viewport-${width}x${height}.png`, import.meta.url).pathname.replace(/^\/(\w:)/,'$1'), fullPage: true });
  }
  await page.setViewportSize({width:360,height:800});
  check(await page.locator('[data-path-viewport]').isVisible(), 'Phone retains an interactive graph');
  await selectCourse('QM');
  await page.waitForTimeout(80);
  check(await selected() === 'QM', 'Phone selects QM');
  check(await page.locator('[data-course-detail="QM"] .path-lecture-list').getAttribute('open') === null, 'Long lecture list is collapsed initially');
  const detailHeading = await page.locator('[data-course-detail="QM"] h2').boundingBox();
  check(detailHeading.y >= 64 && detailHeading.y < 260, 'Phone keeps selected course heading clear of the fixed header');
  await page.locator('[data-path-focus]').click();
  check(await page.locator('.path-node:visible').count() < 24, 'Phone focus filters its graph');
  await page.screenshot({path:new URL('./phone-selected.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true});
  const lecture = page.locator('[data-course-detail="QM"] a[href^="/viewer/"]').first();
  await page.locator('[data-course-detail="QM"] .path-lecture-list summary').click();
  const href = await lecture.getAttribute('href');
  check(new URL(href,base).searchParams.get('file').includes('rongyu-lecture-assets'), 'Existing lecture asset source preserved');
  await lecture.click(); await page.waitForURL('**/viewer/**');
  check(await page.locator('body').count() === 1, 'Course lecture opens existing reader');
  await page.goBack(); await ready();
  check(await selected() === 'QM', 'Reader back restores course state after Astro transition');
  await page.goto(`${base}/latex/`);
  check(await page.locator('[data-lecture-card]').count() > 0, 'Archive lecture list renders');
  await page.locator('[data-filter-group="course"][data-filter-value="QM"]').click();
  check(await page.locator('[data-lecture-card]:visible').count() > 0, 'Existing course filter works');
  await page.locator('a[href="/latex/pathways/"]').click(); await ready();
  await selectCourse('GR'); check(await selected() === 'GR', 'Archive entry and Astro re-entry work');
  await page.reload(); await ready();
  check(await page.locator('audio').evaluateAll(els => els.every(e => e.paused)), 'Music remains off after full reload');
  await page.goto(`${base}/`);
  check(await page.locator('.home-bulletin__item').first().locator('h3').textContent() === '课程学习路径现已上线', 'New course-path announcement is first');
  check(await page.locator('.home-bulletin__item').first().locator('strong').textContent() === '置顶', 'New announcement is marked pinned');
  check(await page.locator('.home-bulletin__item').first().locator('a[href="/latex/pathways/"]').count() === 1, 'Pinned announcement links to course graph');
  await page.goto(`${base}/latex/pathways/`); await ready();
  await page.setViewportSize({width:1440,height:900});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await reset();
  await selectCourse('QM'); await selectCourse('GR');
  await page.waitForTimeout(240);
  check(await page.locator('[data-course-paths]').evaluate(root => root.getAnimations({subtree:true}).every(a => a.playState !== 'running')), 'Normal motion settles without perpetual animation');
  await page.locator('[data-relation="soft"]').click();
  await page.locator('[data-path-focus]').click();
  await page.locator('[data-path-viewport]').scrollIntoViewIfNeeded();
  await page.screenshot({path:new URL('./desktop-focused.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});
  check(errors.length === 0, `No runtime errors: ${errors.join('; ')}`);
} finally {
  writeFileSync(new URL('./browser-results.json', import.meta.url), JSON.stringify({ results, errors }, null, 2));
  console.log(JSON.stringify({passed:results.filter(r=>!r.startsWith('50 selections:')).length,results,errors},null,2));
  await browser.close();
}
