import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PATHWAYS_BASE || 'http://127.0.0.1:4322';
const browser = await chromium.launch({channel:'msedge',headless:true});
const results = [], errors = [];
const check = (ok, label) => { assert(ok,label); results.push(label); };
const data = JSON.parse(readFileSync(new URL('../../src/data/course-paths.json',import.meta.url)));
check(createHash('sha256').update(JSON.stringify(data.edges)).digest('hex') === '42ffe3bc960092ffdec840808edf3aee0d1d811f8dd9b8b4f7f52e2308fe77bb', 'All 55 relationship types, directions and reasons unchanged');
const state = page => page.locator('[data-path-viewport]').evaluate(e=>({scale:Number(e.dataset.zoom),x:Number(e.dataset.panX),y:Number(e.dataset.panY)}));
const settled = page => page.waitForTimeout(50);
const selected = page => page.locator('[data-course-detail]:visible').getAttribute('data-course-detail');
const screenshot = (page,name) => page.screenshot({path:new URL(`./${name}.png`,import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});

try {
  const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${base}/latex/pathways/`); await page.waitForSelector('[data-path-viewport][data-zoom]');
  check(await page.locator('[data-track]').count()===7,'Seven row bands rendered');
  check(await page.locator('.path-row-nav, .path-track__label, .path-index').count()===0,'Category navigation, row labels and duplicate course table removed');
  check(!await page.locator('.path-node').allTextContents().then(texts=>texts.some(t=>t.includes('有讲义'))),'No availability text in graph cards');
  for (const course of data.courses) {
    check(await page.locator(`.path-node[data-course=${course.code}]`).getAttribute('data-category')===course.category,`${course.code} node category correct`);
    await page.locator(`.path-node[data-course=${course.code}]`).dispatchEvent('click');
    check(await page.locator(`[data-course-detail=${course.code}] [data-detail-category]`).textContent()===data.categories.find(c=>c.id===course.category).titleZh,`${course.code} detail category correct`);
  }
  await page.goto(`${base}/latex/pathways/`); await page.waitForSelector('[data-path-viewport][data-zoom]');
  check((await state(page)).scale===.5,'Desktop initially fits the full graph at 50%');
  check(await page.locator('[data-relation][aria-pressed=true]').getAttribute('data-relation')==='hard','Hard prerequisites are the default mode');
  await page.locator('[data-zoom=read]').click(); await settled(page);
  const viewport=page.locator('[data-path-viewport]'); await viewport.scrollIntoViewIfNeeded();
  let box=await viewport.boundingBox();
  const anchor={x:box.x+box.width/2,y:box.y+box.height/2};
  await page.mouse.move(anchor.x,anchor.y);
  let before=await state(page), oldScroll=await page.evaluate(()=>scrollY);
  await page.mouse.wheel(0,-120); await settled(page); let after=await state(page);
  check(Math.abs(after.scale-before.scale-.1)<.001,'Mouse wheel up changes zoom by exactly 10%');
  check(Math.abs((box.width/2-1-before.x)/before.scale-(box.width/2-1-after.x)/after.scale)<2,'Wheel preserves content under cursor (x)');
  check(Math.abs((box.height/2-1-before.y)/before.scale-(box.height/2-1-after.y)/after.scale)<2,'Wheel preserves content under cursor (y)');
  check(await page.evaluate(()=>scrollY)===oldScroll,'Wheel over graph does not scroll page');
  await page.mouse.wheel(0,120); await settled(page);
  check(Math.abs((await state(page)).scale-before.scale)<.001,'Mouse wheel down changes zoom by exactly 10%');
  await page.mouse.move(10,400); before=await state(page);
  await page.mouse.wheel(0,160); await settled(page);
  check((await state(page)).scale===before.scale,'Wheel outside graph leaves graph scale unchanged');
  await page.locator('[data-zoom=read]').click(); await settled(page);
  await viewport.scrollIntoViewIfNeeded();
  const node=page.locator('.path-node[data-course=CM]');
  let nb=await node.boundingBox(); before=await state(page);
  await page.mouse.move(nb.x+nb.width/2,nb.y+nb.height/2); await page.mouse.down();
  await page.mouse.move(nb.x+nb.width/2-95,nb.y+nb.height/2-25,{steps:8}); await page.mouse.up(); await settled(page);
  check((await state(page)).x<before.x-60,`Left-button drag starting on a card pans graph (${before.x} → ${(await state(page)).x})`);
  check(await page.locator('[data-path-welcome]').isVisible(),'Card drag does not select course');
  check(!await viewport.evaluate(e=>e.classList.contains('is-dragging')),'Mouse release clears drag state');
  await node.click();
  check(await selected(page)==='CM','Card tap after drag selects accurately');
  await page.locator('[data-relation=soft]').click();
  check(await page.locator('[data-relation][aria-pressed=true]').getAttribute('data-relation')==='soft','Soft mode is mutually exclusive');
  await page.locator('[data-relation=all]').click();
  check(await page.locator('[data-relation][aria-pressed=true]').getAttribute('data-relation')==='all','All mode is mutually exclusive');
  check(await page.locator('[data-edge-kind=hard]:not(.is-hidden)').count()>0 && await page.locator('[data-edge-kind=soft]:not(.is-hidden)').count()>0,'All mode enables both edge types');
  await page.locator('[data-path-focus]').click();
  await viewport.focus(); await page.keyboard.press('+'); await settled(page);
  before=await state(page); await page.keyboard.press('ArrowRight'); await settled(page);
  check((await state(page)).x<before.x,'Arrow key pans graph');
  await page.keyboard.press('Home'); await settled(page);
  check((await state(page)).scale<1,'Home fits complete seven-row diagram');
  await screenshot(page,'seven-rows-desktop');
  await page.close();

  for (const [label,width,height,mobile] of [['phone',390,844,true],['tablet',768,1024,true],['touch-laptop',1366,900,false]]) {
    const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:mobile,reducedMotion:'reduce'});
    const p=await context.newPage(); p.on('pageerror',e=>errors.push(`${label}: ${e.message}`));
    const cdp=await context.newCDPSession(p);
    await p.goto(`${base}/latex/pathways/`); await p.waitForSelector('[data-path-viewport][data-zoom]');
    const initialScale=(await state(p)).scale;
    check(initialScale === (label==='phone' ? .2 : label==='tablet' ? .4 : .5),`${label}: initial graph fits the viewport`);
    const vp=p.locator('[data-path-viewport]');
    await p.locator('[data-zoom=read]').click(); await vp.scrollIntoViewIfNeeded(); await settled(p);
    const b=await vp.boundingBox(), cx=b.x+b.width/2, cy=Math.min(height-110,b.y+b.height/2);
    const touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([id,x,y])=>({id,x,y,radiusX:4,radiusY:4,force:1}))});
    const oldState=await state(p), sy=await p.evaluate(()=>scrollY);
    await touch('touchStart',[[1,cx-40,cy],[2,cx+40,cy]]);
    await touch('touchMove',[[1,cx-65,cy],[2,cx+65,cy]]); await settled(p);
    const pinched=await state(p);
    check(pinched.scale>oldState.scale*1.4,`${label}: real browser multi-touch spreads to zoom in`);
    check(Number.isInteger(Math.round(pinched.scale*100)/10),`${label}: pinch remains on a 10% zoom step`);
    const ax=cx-b.x-1,ay=cy-b.y-1;
    check(Math.abs((ax-oldState.x)/oldState.scale-(ax-pinched.x)/pinched.scale)<3,`${label}: pinch keeps midpoint content (x)`);
    check(Math.abs((ay-oldState.y)/oldState.scale-(ay-pinched.y)/pinched.scale)<3,`${label}: pinch keeps midpoint content (y)`);
    await touch('touchMove',[[1,cx-50,cy+20],[2,cx+80,cy+20]]); await settled(p);
    let movedState=await state(p);
    check(movedState.y>pinched.y+10,`${label}: two-finger midpoint also pans`);
    await touch('touchMove',[[1,cx-20,cy+20],[2,cx+50,cy+20]]); await settled(p);
    check((await state(p)).scale<movedState.scale,`${label}: pinch inward zooms out`);
    await touch('touchEnd',[[1,cx-20,cy+20]]); await settled(p);
    const single=await state(p);
    await touch('touchMove',[[2,cx+10,cy-10]]); await settled(p);
    const afterSingle=await state(p);
    check(afterSingle.x<single.x-20,`${label}: pinch-to-one-finger transition continues panning`);
    await touch('touchEnd',[]); await settled(p);
    check(await p.locator('[data-path-welcome]').isVisible(),`${label}: pinch never selects a course`);
    check(await p.evaluate(()=>scrollY)===sy,`${label}: graph gesture does not move page`);
    check(!await vp.evaluate(e=>e.classList.contains('is-dragging')),`${label}: gesture end clears dragging`);
    // Cancellation followed by a new gesture must remain usable.
    await touch('touchStart',[[1,cx,cy]]); await touch('touchMove',[[1,cx-30,cy-20]]); await touch('touchCancel',[]);
    check(!await vp.evaluate(e=>e.classList.contains('is-dragging')),`${label}: cancellation releases interaction state`);
    await vp.scrollIntoViewIfNeeded();
    const visibleCode=await p.locator('.path-node').evaluateAll(nodes=>{
      const viewport=document.querySelector('[data-path-viewport]').getBoundingClientRect();
      return nodes.find(node=>{const r=node.getBoundingClientRect();return r.left>=viewport.left&&r.right<=viewport.right&&r.top>=viewport.top&&r.bottom<=viewport.bottom})?.dataset.course;
    });
    const course=p.locator(`.path-node[data-course=${visibleCode}]`); const cb=await course.boundingBox();
    await p.touchscreen.tap(cb.x+cb.width/2,cb.y+cb.height/2); await settled(p);
    check(await selected(p)===visibleCode,`${label}: touch tap after pinch selects correct course`);
    await p.locator('[data-return-map]').click(); await settled(p);
    check(await vp.isVisible(),`${label}: return-to-map action available`);
    check((await p.locator('[data-zoom=fit]').boundingBox()).y >= (width <= 760 ? 64 : 72),`${label}: return keeps zoom toolbar below fixed header`);
    const mapState=await state(p);
    check(mapState.scale>0 && mapState.scale<=2.4,`${label}: camera state remains bounded`);
    check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${label}: no page overflow`);
    await screenshot(p,`seven-rows-${label}`);
    await context.close();
  }
  check(errors.length===0,'No runtime exceptions in mouse or touch contexts');
} finally {
  writeFileSync(new URL('./gesture-results.json',import.meta.url),JSON.stringify({passed:results.length,results,errors},null,2));
  console.log(JSON.stringify({passed:results.length,results,errors},null,2));
  await browser.close();
}
